### ISSUE TITLE
`scan` and `scan_iter` stuck to first iteration

### ISSUE THREAD

**Issue by kinoute** [apache/kvrocks#1402] opened 2023-04-25 12:35 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

2.3.0

### Minimal reproduce step

1. Start Kvrocks Docker container:

`docker run -it -p 6666:6666 apache/kvrocks`

2. Populate the database with 200k keys with Python 3.9.13 and the forked version of Redis-py available here : https://github.com/hashlookup/redis-py

```bash
pip install git+https://github.com/hashlookup/redis-py@master
```

```python3
import redis

REDIS = redis.Redis(
    host='0.0.0.0',
    port=6666,
    password='',
    db=0,
    )

# Populate Kvrocks with 200k keys
pipe = REDIS.pipeline()

for i in range(200_000):
    pipe.set(f'dba_{i}', 1)

pipe.execute()

# Test "scan_iter"
for key in scan_iter('dba_*'):
    print(key)


# Test "scan"
cursor = '0'

while True:
    cursor, keys = REDIS.scan(
        cursor=cursor,
        match='dba_*',
    )
    for key in keys:
        print(key)

    if not keys:
        break
```

### What did you expect to see?

I expected both commands to iterate through every `dba_*` key.

### What did you see instead?

Instead, both commands are stuck on the first iteration of default size and keep printing the same batch of keys every time.

Exemple with `scan_iter`:

```
b'dba_0'
b'dba_1'
b'dba_10'
b'dba_100'
b'dba_1000'
b'dba_10000'
b'dba_100000'
b'dba_100001'
b'dba_100002'
b'dba_100003'
b'dba_100004'
b'dba_100005'
b'dba_100006'
b'dba_100007'
b'dba_100008'
b'dba_100009'
b'dba_10001'
b'dba_100010'
b'dba_100011'
b'dba_100012'
b'dba_1'
b'dba_10'
b'dba_100'
b'dba_1000'
b'dba_10000'
b'dba_100000'
b'dba_100001'
b'dba_100002'
b'dba_100003'
b'dba_100004'
b'dba_100005'
b'dba_100006'
b'dba_100007'
b'dba_100008'
b'dba_100009'
b'dba_10001'
b'dba_100010'
b'dba_100011'
b'dba_100012'
b'dba_100013'
b'dba_1'
b'dba_10'
b'dba_100'
b'dba_1000'
b'dba_10000'
b'dba_100000'
b'dba_100001'
b'dba_100002'
b'dba_100003'
b'dba_100004'
b'dba_100005'
b'dba_100006'
b'dba_100007'
b'dba_100008'
b'dba_100009'
b'dba_10001'
b'dba_100010'
b'dba_100011'
b'dba_100012'
b'dba_100013'
```

etc.

### Anything Else?

While being inefficient, `keys` doesn't suffer from this problem and return every key matching the pattern:

```python3
len(REDIS.keys('dba_*'))

200000
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by kinoute** [comment] 2023-04-25 12:47
it works when we use this "obscure" python package : https://pypi.org/project/kvrocks-scan/

Which does the following:

```python3
import redis

def parse_scan(response, **options):
	cursor, r = response
	if cursor == b"0" or cursor == "0":
		return int(cursor),r;
	return cursor, r

redis.client.AbstractRedis.RESPONSE_CALLBACKS["SCAN"] = parse_scan;


# Redis scan_iter etc
```

I'm not sure why this works and the forked Redis python by @hashlookup, which seems to handle this int/str cast, doesn't.

Edit: Actually, with this method, `scan_iter` is stuck in an infinite loop. `scan` seems to work correctly.

**Comment by git-hulk** [comment] 2023-04-25 13:51
Hi, @kinoute 

Thanks for your feedback, we would take a look.

**Comment by git-hulk** [comment] 2023-04-26 03:27
@kinoute The root cause is right that the Kvrocks scan command would return a string cursor instead of the integer, so it's not compatible with the official Python client. Another workaround can use the raw client to send and parse the scan command.

For why the scan_iter didn't, to see if @adulau or other guys who are familiar with Python can help.

**Comment by kinoute** [comment] 2023-04-26 06:33
But it seems the forked Redis-py client the Kvrocks team recommends in many issues should handle this problem? See this commit: https://github.com/redis/redis-py/commit/e9c53fb1398e636106c0ec0165ba564943564a83

Or am I missing something here?

**Comment by git-hulk** [comment] 2023-04-26 06:43
Yes, we recommend using the fork redis-py, and it should be fine to add a wrap function to work around this.

**Comment by jihuayu** [comment] 2023-05-31 13:00
The Redis documentation clearly states that the cursor is unsigned 64 bit number. Do we not need to fully compatible with Redis protocol?
[Scan commands return value section](https://redis.io/commands/scan/#:~:text=the%20first%20element%20is%20a%20string%20representing%20an%20unsigned%2064%20bit%20number)

**Comment by infdahai** [comment] 2023-05-31 16:33
I approve your point.@jihuayu

**Comment by git-hulk** [comment] 2023-06-01 02:00
@jihuayu The underly storage is different between Kvrocks and Redis, so what we can do is try our best to be compatible with Redis. Welcome to submit the proposal if you have any ideas to achieve this.

**Comment by jihuayu** [comment] 2023-06-04 10:58
@git-hulk  SCAN commond is frequently used in Redis clients.It's important to ensure SCAN commond is correct for Redis toolchains to work with Kvrocks. 
Therefore, I believe this issue needs to be resolved.

After carefully reading the Redis documentation, I found that cursors have the following features:

1. The cursor is a 64-bit unsigned integer, with 0 meaning the end of the iteration. 
2. There is no state server side, the full state is captured by the cursor
3. During the iteration process, a given element may be returned multiple times.
4. As long as the number of elements is not constantly increasing, the iteration will eventually end.
5. Use a corrupted cursor is undefined behavior.


Therefore, I think we can use a **ring array** to store the key names for the most recently used cursors.

When SCAN end_cursor is "keyname1" we push {key:keyname1,cursor:1276} to cursor-ring.
Next SCAN use cursor 1276, we foreach cursor-ring from the newest item, and get the it's key "keyname1". I call this process cursor translation.
Then we can use "keyname1" to seek rocksdb iterator.

If client call many SCAN command, cursor-ring will be filled and the oldest cursor will be discarded.
Now the if client SCAN use a corrupted cursor(the cursor don't in cursor-ring), we will return element from begin.

Based on the above design, we will have the following additional costs.

1. Less than 2KB of memory is used to store the cursor ring.
2. Each SCAN request requires one cursor translation and one cursor mapping save. (Note: Ensuring thread safety is required for cursor mapping save) 

Because SCAN command is a slow command, so the additional cursor translation has a minimal impact.

**Comment by git-hulk** [comment] 2023-06-04 13:28
@jihuayu Thanks for your solution. 

The ring buffer or LRU cache is good for me. For the HSCAN and SSCAN commands, we need to use the subkey to map the string cursor and number.

By the way, to be compatible with the older version, we should add a configuration to allow users to enable this feature. And can enable it by default in the next major version.

**Comment by jihuayu** [comment] 2023-06-06 06:09
@git-hulk Ok, I will send a PR later. You can assign this task to me.

https://github.com/apache/incubator-kvrocks/issues/877 It may be solved together.

**Comment by git-hulk** [comment] 2023-06-06 06:10
Thanks @jihuayu, assigned

**Comment by mapleFU** [comment] 2023-06-09 15:41
Nice catch! @jihuayu

1. What if `"keyname1"` is deleted after cursor put into ring array?
2. How does the `cursor:1276` number generated?

**Comment by jihuayu** [comment] 2023-06-09 23:54
Thank you! @mapleFU 
1. I'm not storing the iterator, I just made a dictionary that [converts the **number cursor** to a **begin key name**](https://github.com/jihuayu/incubator-kvrocks/blob/71358a1b6260ba6a9dd91ac2930e3f3645fa4d6d/src/commands/cmd_server.cc#L777) when receiving the command. After completing the scan, I use [the **end key name** to generate a new **number cursor**](https://github.com/jihuayu/incubator-kvrocks/blob/71358a1b6260ba6a9dd91ac2930e3f3645fa4d6d/src/commands/cmd_server.cc#L765).
2. [The cursor is a global counter that is incremented whenever a new cursor needs to be generated.](https://github.com/jihuayu/incubator-kvrocks/blob/71358a1b6260ba6a9dd91ac2930e3f3645fa4d6d/src/server/server.cc#L1768)

**Closed as completed** 2023-06-25 11:54 UTC
Labels: bug
