### ISSUE TITLE
Tracking issue for build system enhancements

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#575] opened 2022-05-12 07:45 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Modern CMake provides many amazing features to organize the build structure of a project in a more convenient way, and we can make full use of them to improve the development experience!
@tisonkun had a good suggestion in https://github.com/apache/incubator-kvrocks/issues/562#issuecomment-1123771508 of creating a tracking issue to help keep the discussion more focused, so this issue is created for that purpose.

### Solution

The list below tracks some of the improvements that have been proposed so far, and I'd appreciate it if anyone came up with new ideas for improvements, PRs for current improvements, or participated in this discussion!

- [x] #561
- [x] #562
- [x] #574
- [x] #569
- [x] #563
- [x] #580
- [x] #589
- [x] #590

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by torwig** [comment] 2022-05-12 13:25
I'm trying to build kvrocks on Fedora35 with CMake (cmake version 3.22.2):

```
mkdir build
cd build
cmake ../
make -j8

[ 96%] Linking CXX executable kvrocks
[ 96%] Building CXX object CMakeFiles/kvrocks2redis.dir/tools/kvrocks2redis/sync.cc.o
[ 96%] Building CXX object CMakeFiles/kvrocks2redis.dir/tools/kvrocks2redis/redis_writer.cc.o
[ 96%] Building CXX object CMakeFiles/unittest.dir/tests/string_util_test.cc.o
[ 97%] Building CXX object CMakeFiles/unittest.dir/tests/rwlock_test.cc.o
[ 97%] Building CXX object CMakeFiles/unittest.dir/tests/cron_test.cc.o
[ 97%] Building CXX object CMakeFiles/kvrocks2redis.dir/tools/kvrocks2redis/writer.cc.o
[ 98%] Building CXX object CMakeFiles/kvrocks2redis.dir/tools/kvrocks2redis/parser.cc.o
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/kvrocks.dir/build.make:761: kvrocks] Error 1
make[1]: *** [CMakeFiles/Makefile2:314: CMakeFiles/kvrocks.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Building CXX object CMakeFiles/unittest.dir/tests/config_test.cc.o
[ 98%] Building CXX object CMakeFiles/unittest.dir/tests/task_runner_test.cc.o
[ 98%] Building CXX object CMakeFiles/unittest.dir/tests/t_bitmap_test.cc.o
[ 98%] Building CXX object CMakeFiles/unittest.dir/tests/compact_test.cc.o
[100%] Building CXX object CMakeFiles/unittest.dir/tests/log_collector_test.cc.o
[100%] Building CXX object CMakeFiles/unittest.dir/src/sha1.cc.o
[100%] Building CXX object CMakeFiles/unittest.dir/src/rand.cc.o
[100%] Linking CXX executable kvrocks2redis
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/kvrocks2redis.dir/build.make:841: kvrocks2redis] Error 1
make[1]: *** [CMakeFiles/Makefile2:346: CMakeFiles/kvrocks2redis.dir/all] Error 2
[100%] Linking CXX executable unittest
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/unittest.dir/build.make:1067: unittest] Error 1
make[1]: *** [CMakeFiles/Makefile2:380: CMakeFiles/unittest.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```


However, just doing `make -j8` successfully builds the application.

**Comment by PragmaTwice** [comment] 2022-05-12 14:06
Can you locate `libstdc++.a` in your environment?
Refer to [here](https://www.linuxquestions.org/questions/fedora-35/fedora-22-ld-cannot-find-lstdc-4175555440/), the command in fedora maybe `dnf provides */libstdc++.a`, and you could try to install `libstdc++-static`.

https://unix.stackexchange.com/questions/416875/fedora-27-usr-bin-ld-cannot-find-lstdc

**Comment by PragmaTwice** [comment] 2022-05-12 14:13
The problem is caused by that `-static-libstdc++` is added as a flag to the compiler in [CMakeLists.txt#L72](https://github.com/apache/incubator-kvrocks/blob/unstable/CMakeLists.txt#L72), which is not added in makefiles, so a static library of libstdc++ is needed.

**Comment by PragmaTwice** [comment] 2022-05-12 14:27
> The problem is caused by that `-static-libstdc++` is added as a flag to the compiler in [CMakeLists.txt#L72](https://github.com/apache/incubator-kvrocks/blob/unstable/CMakeLists.txt#L72), which is not added in makefiles, so a static library of libstdc++ is needed.

Maybe some tips should be added to README to let users know that kvrocks need libstdc++.a for build. @git-hulk

**Comment by git-hulk** [comment] 2022-05-12 14:55
> > The problem is caused by that `-static-libstdc++` is added as a flag to the compiler in [CMakeLists.txt#L72](https://github.com/apache/incubator-kvrocks/blob/unstable/CMakeLists.txt#L72), which is not added in makefiles, so a static library of libstdc++ is needed.
> 
> Maybe some tips should be added to README to let users know that kvrocks need libstdc++.a for build. @git-hulk

Yes, you are right. Do you think it's a good idea to search library first before linking?

**Comment by torwig** [comment] 2022-05-12 15:25
@PragmaTwice 
Thank you, `sudo dnf install libstdc++-static` solved the issue, and now the application is successfully built.

**Comment by PragmaTwice** [comment] 2022-05-12 16:56
> > > The problem is caused by that `-static-libstdc++` is added as a flag to the compiler in [CMakeLists.txt#L72](https://github.com/apache/incubator-kvrocks/blob/unstable/CMakeLists.txt#L72), which is not added in makefiles, so a static library of libstdc++ is needed.
> > 
> > 
> > Maybe some tips should be added to README to let users know that kvrocks need libstdc++.a for build. @git-hulk
> 
> Yes, you are right. Do you think it's a good idea to search library first before linking?

I think it is a good idea, there are two solutions for searching library:
1. find library, and give an error or warning if not found; give an option to user of whether `-static-libstdc++` is enabled
2. find library, do not enable `-static-libstdc++` if not found

I prefer the first solution, because I think the second is more implicit, users may not know whether `-static-libstdc++` is enabled while they are building the project (it is totally depend on the environment).

**Comment by git-hulk** [comment] 2022-05-13 01:39
agree, explicitly always better than implicitly.

**Comment by git-hulk** [comment] 2022-05-16 14:14
I try to build on CentOS8(also CentOS7) and got the error:
```
/root/incubator-kvrocks/build/_deps/jemalloc-src/include/jemalloc/internal/rtree.h:109:19: error: variably modified ‘root’ at file scope
  rtree_leaf_elm_t root[1U << (RTREE_NSB/RTREE_HEIGHT)];
```
But I didn't find the root cause, just commented first.

**Comment by git-hulk** [comment] 2022-05-16 16:27
> I try to build on CentOS8(also CentOS7) and got the error:
> 
> ```
> /root/incubator-kvrocks/build/_deps/jemalloc-src/include/jemalloc/internal/rtree.h:109:19: error: variably modified ‘root’ at file scope
>   rtree_leaf_elm_t root[1U << (RTREE_NSB/RTREE_HEIGHT)];
> ```
> 
> But I didn't find the root cause, just commented first.

It also failed on the old version, so NOT related with the new build system.

**Comment by PragmaTwice** [comment] 2022-05-16 16:54
That's weird. I think it is probably due to the macro `RTREE_NSB` or `RTREE_HEIGHT`, which are original `LG_VADDR` and `LG_PAGE`. Could you check your `include/jemalloc/internal/jemalloc_internal_defs.h` generated by `configure` which includes these two macro definition?
And sometimes try clang or other version of gcc could let you find some useful info.

**Comment by git-hulk** [comment] 2022-05-17 00:37
I checked the generated defs, looks the `LG_VADDR` shouldn't be 0:
```c
#define LG_VADDR 0

/* One page is 2^LG_PAGE bytes. */
#define LG_PAGE 12
```
I will compare the normal version on ubuntu later.

**Comment by PragmaTwice** [comment] 2022-05-17 03:30
```
$ bat include/jemalloc/internal/jemalloc_internal_defs.h | rg "LG_(VADDR|PAGE)"
#define LG_VADDR 48
/* One page is 2^LG_PAGE bytes. */
#define LG_PAGE 12
```
These two macro definition in my side. Maybe the reason is that `0` can lead `RTREE_NSB` to be a negative number.

> In any case, if the value of the right operand is negative or is greater or equal to the number of bits in the promoted left operand, the behavior is undefined.

Refer to https://en.cppreference.com/w/cpp/language/operator_arithmetic#Bitwise_shift_operators, that's an UB.

**Comment by git-hulk** [comment] 2022-05-17 04:03
Yes, you're right. I also find this on my side and this only appears in MacOSX docker environment.

**Comment by tisonkun** [comment] 2022-06-02 08:21
Given that all subtasks done, @PragmaTwice do you think that we can close this issue as resolved?

**Comment by PragmaTwice** [comment] 2022-06-02 11:56
> Given that all subtasks done, @PragmaTwice do you think that we can close this issue as resolved?

Yeah, althought there is some issue in #615, I temporarily have no more enhancement idea, so I think we can close it since all of these enhancements are done.

**Closed as completed** 2022-06-02 12:06 UTC
Labels: enhancement
