### ISSUE TITLE
Flaky test in HNSW index unit test

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#2550] opened 2024-09-21 11:28 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

See https://github.com/apache/kvrocks/actions/runs/10971334789/job/30466698610?pr=2538#step:15:173

### What did you expect to see?

CI passed

### What did you see instead?

CI failure

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by LindaSummer** [comment] 2024-09-22 11:29
Hi @git-hulk ,

I want to follow up this issue. 😊
Can it be assigned to me?

Best Regards,
Edward

**Comment by git-hulk** [comment] 2024-09-22 11:43
@LindaSummer Sure, thank you!

**Comment by LindaSummer** [comment] 2024-09-26 09:35
Hi @Beihao-Zhou ,

Sorry to bother you.
Please correct me if my analysis is incorrect. 😊

The GitHub Action's log is `Layer: 4 Frequency: 458 Expected: 411.52266242457773`.
If I understand correctly, this expected value should be $(3{^-4}-3{^-5})*50000=411.5226337448559$.

Since we use a random seed from `random_device`.
https://github.com/apache/kvrocks/blob/f2bc224bc342f7e2b679cb2dc79d7a31067643ca/src/search/hnsw_indexer.cc#L180-L181

We can't reproduce the same generation sequence and in my knowledge the generation result may not be same as expected.

Could I use a fixed rand seed for unit test startup initialization to solve this issue?

I think it will improve the reproducing ability for test cases.

Best Regards,
Edward

**Comment by Beihao-Zhou** [comment] 2024-09-26 12:07
Thanks for looking into the issue! @LindaSummer 
Yes sure, I think you can change the interface a bit to pass in the fixed seed. For the current unit tests, I just set a relatively low threshold so that in majority times it can pass even if it's randomized. 
Thanks again for fixing it!

**Closed as completed** 2024-09-27 10:35 UTC
Labels: bug
