### ISSUE TITLE
[BUG]  Failed to open DB with missing CURRENT file

### ISSUE THREAD

**Issue by jasonhe88** [apache/kvrocks#437] opened 2021-12-29 07:49 UTC
**Describe the bug**

 - OS: MAC OS 10.15.7
 - Version  2.0.5 @6a4ed16a

get following error message when try to start up kvrocks ( first time run )

E1229 15:41:02.217978 276704704 main.cc:314] Failed to open: IO error: No such file or directory: While opening a file for sequentially reading: /tmp/kvrocks/db/CURRENT: No such file or directory

/tmp/kvrocks directory did exist but no sub-directory ./db under it.

**Comment by caipengbo** [comment] 2021-12-29 07:54
Have you tried to modify the `dir` item in the configuration file?

**Comment by jasonhe88** [comment] 2021-12-29 08:04
> Have you tried to modify the `dir` item in the configuration file?

yes, I modified dir to other directory, still got same msg

**Comment by caipengbo** [comment] 2021-12-29 08:12
You create the directory manually and see if it works.

**Comment by jasonhe88** [comment] 2021-12-29 08:14
> Have you tried to modify the `dir` item in the configuration file?

just tried, still the same

by the way, make test all ok

**Comment by git-hulk** [comment] 2021-12-29 08:20
@jasonhe88 Can u help to check whether `/tmp/kvrocks/db/CURRENT` was existed or not, or have a look at your directory permission.

**Comment by jasonhe88** [comment] 2021-12-29 08:23
> @jasonhe88 Can u help to check whether `/tmp/kvrocks/db/CURRENT` was existed or not, or have a look at your directory permission.

here are all the files under /tmp/kvrocks:

lrwxr-xr-x  1 jasonhe  wheel   63 12 29 16:07 kvrocks.ERROR -> kvrocks.JasoniMac.local.jasonhe.log.ERROR.20211229-160746.77969
lrwxr-xr-x  1 jasonhe  wheel   62 12 29 16:07 kvrocks.INFO -> kvrocks.JasoniMac.local.jasonhe.log.INFO.20211229-160746.77969
-rw-r--r--  1 jasonhe  wheel  341 12 29 15:29 kvrocks.JasoniMac.local.jasonhe.log.ERROR.20211229-152937.72372
-rw-r--r--  1 jasonhe  wheel  341 12 29 15:48 kvrocks.JasoniMac.local.jasonhe.log.ERROR.20211229-154820.76439
-rw-r--r--  1 jasonhe  wheel  341 12 29 16:07 kvrocks.JasoniMac.local.jasonhe.log.ERROR.20211229-160746.77969
-rw-r--r--  1 jasonhe  wheel  411 12 29 15:29 kvrocks.JasoniMac.local.jasonhe.log.INFO.20211229-152937.72372
-rw-r--r--  1 jasonhe  wheel  411 12 29 15:48 kvrocks.JasoniMac.local.jasonhe.log.INFO.20211229-154820.76439
-rw-r--r--  1 jasonhe  wheel  411 12 29 16:07 kvrocks.JasoniMac.local.jasonhe.log.INFO.20211229-160746.77969
-rw-r--r--  1 jasonhe  wheel  341 12 29 15:29 kvrocks.JasoniMac.local.jasonhe.log.WARNING.20211229-152937.72372
-rw-r--r--  1 jasonhe  wheel  341 12 29 15:48 kvrocks.JasoniMac.local.jasonhe.log.WARNING.20211229-154820.76439
-rw-r--r--  1 jasonhe  wheel  341 12 29 16:07 kvrocks.JasoniMac.local.jasonhe.log.WARNING.20211229-160746.77969
lrwxr-xr-x  1 jasonhe  wheel   65 12 29 16:07 kvrocks.WARNING -> kvrocks.JasoniMac.local.jasonhe.log.WARNING.20211229-160746.77969

**Comment by jasonhe88** [comment] 2021-12-29 08:26
> @jasonhe88 Can u help to check whether `/tmp/kvrocks/db/CURRENT` was existed or not, or have a look at your directory permission.

the original permisson is 755, i changed to 777, still same

drwxrwxrwx  14 jasonhe  wheel  448 12 29 16:07 kvrocks

**Comment by jasonhe88** [comment] 2021-12-29 09:40
tried on CentOS 8, same problem

**Comment by git-hulk** [comment] 2021-12-29 10:04
Do you use the release RPM? I have no idea about why this happen since can't reproduce on my side.

**Comment by fishery86** [comment] 2021-12-29 10:18
it seems there have some errors link with rocksdb

**Comment by jasonhe88** [comment] 2021-12-29 10:52
> Do you use the release RPM? I have no idea about why this happen since can't reproduce on my side.

tried release RPM on CentOS8, it's running ok

**Comment by git-hulk** [comment] 2021-12-29 13:04
Many thanks for your feedback, do you follow the pre-install step before installing? 

https://github.com/KvrocksLabs/kvrocks#building-kvrocks

**Comment by jasonhe88** [comment] 2021-12-29 13:16
> Many thanks for your feedback, do you follow the pre-install step before installing?
> 
> https://github.com/KvrocksLabs/kvrocks#building-kvrocks

no problem, thanks to you guys for this great product :-)

I exactly followed the installation steps, except did a check out before make -4j

git checkout v2.0.5

**Comment by git-hulk** [comment] 2021-12-29 13:20
Thanks, I would try to reproduce this issue on my side, very welcome to help us to fix this issue if you have any clues.

**Comment by git-hulk** [comment] 2022-06-04 07:23
I finally reproduced this issue by wrongly linking the compression library,
Kvrocks will ignore the creating column families error and cause failed to
open DB since it didn't auto create the db dir. This will be fixed by #620.

**Closed as completed** 2022-06-06 11:03 UTC
