### ISSUE TITLE
Docker container exits with code 132 and no output

### ISSUE THREAD

**Issue by SamSpiri** [apache/kvrocks#1146] opened 2022-11-28 14:22 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

Ubuntu 20.04.1 LTS \n \l
Linux home 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Docker version 19.03.5, build 633a0ea838

docker image apache/kvrocks:2.2.0

### Minimal reproduce step

$ docker run -i --rm apache/kvrocks:2.2.0
$ echo $?
132

### What did you expect to see?

1. Output logs with the reason why kvrocks exited
2. Kvrocks don't exit but works

### What did you see instead?

no logs, no output, just exit 132

### Anything Else?

tried tags nightly, 2.1.0 with same bad result.
but kvrocks/kvrocks:latest image did output version number and worked until i triggered CTRL-C:
```
$ docker run -i --rm kvrocks/kvrocks
Version: 2.0.6 @4e5883e9
^C
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment] 2022-11-28 14:56
Hi, I am afraid kvrocks aborted due to the `Illegal Instruction` (128 + 4) signal, that is, the kvrocks executable binary in the docker image uses some instruction sets which is not supported by your cpu (in x64, it may be avx512 or something, you can use gdb to determine the concrete instruction which leads to termination).

I will investigate this problem, and you can build kvrocks on your local device to avoid this problem. (or build the docker image on your local.)

**Comment by SamSpiri** [comment] 2022-11-28 17:16
> not supported by your cpu 

I tried on intel and it also worked until i triggered CTRL-C,
but it didn't produce any output while running and then before exiting it prints all the logs.
That's my main concern, because i have no logs of kvrocks in my kubernetes.
```
$ docker run -i --rm apache/kvrocks:2.2.0
^CI20221128 17:10:47.559381     1 main.cc:306] kvrocks version 2.2.0 @17b31e7
I20221128 17:10:47.606953     1 storage.cc:326] [storage] Success to load the data from disk: 21 ms
I20221128 17:10:47.608379     1 worker.cc:67] [worker] Listening on: 0.0.0.0:6666
I20221128 17:10:47.608695     1 worker.cc:67] [worker] Listening on: 0.0.0.0:6666
I20221128 17:10:47.608955     1 worker.cc:67] [worker] Listening on: 0.0.0.0:6666
I20221128 17:10:47.609221     1 worker.cc:67] [worker] Listening on: 0.0.0.0:6666
I20221128 17:10:47.609475     1 worker.cc:67] [worker] Listening on: 0.0.0.0:6666
I20221128 17:10:47.609719     1 worker.cc:67] [worker] Listening on: 0.0.0.0:6666
I20221128 17:10:47.609954     1 worker.cc:67] [worker] Listening on: 0.0.0.0:6666
I20221128 17:10:47.610208     1 worker.cc:67] [worker] Listening on: 0.0.0.0:6666
I20221128 17:10:47.610711     1 worker.cc:483] [worker] Thread #140263785711360 started
I20221128 17:10:47.610746     1 worker.cc:483] [worker] Thread #140263794104064 started
I20221128 17:10:47.610776     1 worker.cc:483] [worker] Thread #140263802496768 started
I20221128 17:10:47.610828     1 worker.cc:483] [worker] Thread #140263878031104 started
I20221128 17:10:47.610872     1 worker.cc:483] [worker] Thread #140263869638400 started
I20221128 17:10:47.610915     1 worker.cc:483] [worker] Thread #140263861245696 started
I20221128 17:10:47.610956     1 worker.cc:483] [worker] Thread #140263852852992 started
I20221128 17:10:47.610994     1 worker.cc:483] [worker] Thread #140263844460288 started
I20221128 17:10:47.611133     1 server.cc:190] Ready to accept connections
I20221128 17:10:49.275743     1 main.cc:59] Bye Bye
```

Previously it crashed on the old AMD:
```
vendor_id	: AuthenticAMD
cpu family	: 21
model		: 48
model name	: AMD Athlon(tm) X4 860K Quad Core Processor
stepping	: 1
microcode	: 0x6003106
cpu MHz		: 1792.078
cache size	: 2048 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 2
apicid		: 19
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb bpext ptsc cpb hw_pstate ssbd vmmcall fsgsbase bmi1 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold overflow_recov
bugs		: fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 7386.96
TLB size	: 1536 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro [13]
```

**Comment by git-hulk** [comment] 2022-11-29 02:46
@SamSpiri You can run `docker run -it --rm -p 6666:6666 apache/kvrocks:2.2.0` that specified the `-t` option to allocate a pseudo-TTY, then you should see the output if all goes smoothly.

**Comment by SamSpiri** [comment] 2022-11-29 11:46
yep! with tty all goes smoothly.
It also worked for me in Kubernetes, now i get logs from the start. I just added one line "tty: true":
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-kvrocks
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.fullname" . }}-kvrocks
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.fullname" . }}-kvrocks
    spec:
      containers:
        - name: kvrocks
          image: {{ .Values.kvrocks.image }}
          tty: true
          ports:
            - containerPort: 8888
          resources:
            {{- toYaml .Values.kvrocks.resources | nindent 12 }}
          command:
            - /bin/sh
            - -c
            - |-
                cd /kvrocks
                cp conf/kvrocks.conf /tmp
                [ ! -z "$REDIS_AUTH" ] && sed -i -r "s/^(# )?requirepass.*/requirepass $REDIS_AUTH/" conf/kvrocks.conf
                [ ! -z "$WRITE_BUFFER_SIZE" ] && sed -i -r "s/^(# )?rocksdb.write_buffer_size.*/rocksdb.write_buffer_size $WRITE_BUFFER_SIZE/" conf/kvrocks.conf
                exec ./bin/kvrocks -c ./conf/kvrocks.conf
          env:
            - name: WRITE_BUFFER_SIZE
              value: "{{ .Values.kvrocks.write_buffer_size }}"
            - name: REDIS_AUTH
              value: "..."
```

**Comment by git-hulk** [comment] 2022-11-29 13:00
Cool, I will close this issue if no further discussion.

**Closed as completed** 2022-12-02 18:27 UTC
Labels: bug

**Comment by ovaistariq** [comment] 2023-07-19 05:09
The nightly build of kvrocks crashes for me on AMD system. 

```
/ # kvrocks -c /conf/kvrocks.conf
Illegal instruction (core dumped)
/ #
command terminated with exit code 132
```

cpuinfo can be found below

```
vendor_id	: AuthenticAMD
cpu family	: 25
model		: 1
model name	: AMD EPYC
stepping	: 1
microcode	: 0x1000065
cpu MHz		: 2450.000
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr wbnoinvd arat npt nrip_save umip pku ospke vaes vpclmulqdq rdpid
bugs		: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 4900.00
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management:
```

**Comment by git-hulk** [comment] 2023-07-19 05:31
Hi @ovaistariq, thanks for your feedback.

I guess it may be caused by this PR https://github.com/apache/kvrocks/pull/1516 disable the rocksdb portable option. Would you like to have a try at 2.4.0? if it works, this issue should be introduced by the previous PR.

**Comment by ovaistariq** [comment] 2023-07-19 18:20
2.5.0 works fine. So I believe the issue is introduced after 2.5.0?

**Comment by git-hulk** [comment] 2023-07-20 01:31
@ovaistariq Maybe, but I cannot figure out which PR may introduce this issue except #1516(included in 2.5.0). Need to dive into it later.

**Comment by ovaistariq** [comment] 2023-07-20 05:00
@git-hulk it could be related to the PORTABLE flag. So I can try building a running a binary built with `PORTABLE=1`

**Comment by git-hulk** [comment] 2023-07-20 05:18
Yes, we disable this option after #1516, but I'm still confused why 2.5.0 works well.

**Comment by ovaistariq** [comment] 2023-07-20 05:20
Then it could be another change introduced since 2.5.0

**Comment by ovaistariq** [comment] 2023-07-21 05:02
@git-hulk building the binary with `PORTABLE=1` fixes the issue and I no longer see a crash on AMD systems.

**Comment by ovaistariq** [comment] 2023-07-21 05:10
Given the changes [here](https://github.com/facebook/rocksdb/pull/11419/files), I think it is best for the docker image build to be portable.

**Comment by git-hulk** [comment] 2023-07-21 05:14
> Given the changes [here](https://github.com/facebook/rocksdb/pull/11419/files), I think it is best for the docker image build to be portable.

Hi @ovaistariq, huge thanks for your investigation. I think it makes a lot to enable the portable in the docker image. Would you like to submit the PR to fix this?

**Comment by ovaistariq** [comment] 2023-07-21 06:47
Sure, I would be happy to submit a PR

**Comment by git-hulk** [comment] 2023-07-21 06:50
Great, thank you!

**Comment by ovaistariq** [comment] 2023-07-21 06:54
@git-hulk here you go: https://github.com/apache/kvrocks/pull/1602
