### ISSUE TITLE
[BUG] docker image crash

### ISSUE THREAD

**Issue by aberfeldy** [apache/kvrocks#242] opened 2021-05-03 09:03 UTC
**Describe the bug**
Hey!
Tried to run kvrocks with your docker image, but it doesn't start or produce any logs. Docker deamon on Mac and ubuntu (20.0.3 & 20.10.6) both report that the container exited with Code 132. 
So I cloned into the 2.0 branch and build from source and to build the docker image fresh. And then it worked like charm, it logs `Version: 2.0.0 @000b3627` and redis-cli is fine with it.
Did I miss anything while starting the docker container from the README instructions? 

**To Reproduce**
1. docker run -it -p 6666:6666 bitleak/kvrocks

docker inspect ...
```
"State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 132,
            "Error": "",
            "StartedAt": "2021-05-03T09:02:17.8104824Z",
            "FinishedAt": "2021-05-03T09:02:17.8757551Z"
        },

**Comment by git-hulk** [comment] 2021-05-03 13:45
Thanks for your feedback, I also tried that on my side and it's caused by Illegal instruction. I'll work on it and update if has any progress.

**Comment by git-hulk** [comment] 2021-05-03 14:40
Fixed in https://github.com/bitleak/kvrocks/pull/244

**Comment by aberfeldy** [comment] 2021-05-04 07:08
Tried it out right now, got: `Version: 999.999.999 @e28d7ba8`
Love it, thanks a lot!

**Closed as completed** 2021-05-04 08:46 UTC
