### ISSUE TITLE
2.0.6 slaveof 2.3 version can not running

### ISSUE THREAD

**Issue by QQxiaoyuyu** [apache/kvrocks#1317] opened 2023-03-13 05:50 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

2.0.6 slaveof 2.3 can not running
![图片](https://user-images.githubusercontent.com/34185590/224618143-d7f6e32c-8ac7-4f88-9074-7dfc19c0f8c1.png)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by QQxiaoyuyu** [comment] 2023-03-13 07:05
将2.3的storge.cc  stream column family去掉，然后用2.3的数据启动无法启动

**Comment by aleksraiden** [comment] 2023-03-13 10:38
@torwig Could we check this?

**Comment by git-hulk** [comment] 2023-03-13 10:52
There're two problems with this issue:

- For the old version slave cannot be compatible with the newer one since it may miss some column families
- The slave instance should not crash after failing to restore from the DB

**Comment by git-hulk** [comment] 2023-03-14 01:38
The crash line is https://github.com/apache/incubator-kvrocks/blob/2.0/src/server.cc#L496 and the root cause is that the cron thread may use the db pointer which will be null during the restore process.

Thanks for @QQxiaoyuyu information.

**Comment by git-hulk** [comment] 2023-03-14 04:18
I took a look at the implementation, this crash issue has been fixed in https://github.com/apache/incubator-kvrocks/pull/278

**Closed as completed** 2023-03-19 12:00 UTC
Labels: enhancement
