### ISSUE TITLE
Command SRANDMEMBER returns empty array when [count] is a negative number

### ISSUE THREAD

**Issue by sam-hn** [apache/kvrocks#2072] opened 2024-01-30 03:13 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

2.7.0

### Minimal reproduce step

10.70.163.45:6666> srandmember set1 5
1) "mem1"
2) "mem2"
3) "mem3"
10.70.163.45:6666> srandmember set1 -5
(empty array)
10.70.163.45:6666> srandmember set1 -2
(empty array)

### What did you expect to see?

According to https://redis.io/commands/srandmember/, If called with a negative count, the behavior changes and the command is allowed to return the same element multiple times. In this case, the number of returned elements is the absolute value of the specified count

### What did you see instead?

<empty array>

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by jihuayu** [comment] 2024-01-30 03:17
@sam-hn Thank you. 
You can find related code in [this](https://github.com/apache/kvrocks/blob/aa1de3f53252a16e43d381fec83d64ec59228869/src/commands/cmd_set.cc#L190)
And it is better if you can add a [test case](https://github.com/apache/kvrocks/blob/aa1de3f53252a16e43d381fec83d64ec59228869/tests/gocase/unit/type/set/set_test.go#L657)

**Comment by git-hulk** [comment] 2024-01-30 03:19
It has been resolved in https://github.com/apache/kvrocks/pull/2032?

**Comment by jihuayu** [comment] 2024-01-30 03:27
@git-hulk It looks like no. First is Redis, second is kvrocks
![image](https://github.com/apache/kvrocks/assets/32858525/494d4cd9-6f1e-4c36-9ad4-c5af5cf091e9)

**Comment by mapleFU** [comment] 2024-01-30 03:32
```c++
rocksdb::Status Set::Take(const Slice &user_key, std::vector<std::string> *members, int count, bool pop) {
  int n = 0;
  members->clear();
  if (count <= 0) return rocksdb::Status::OK();
```

The problem it's the 4th line... It would be easy to fix

**Comment by git-hulk** [comment] 2024-01-30 03:45
@jihuayu Got it. The issue is still existing while the count parameter was assigned.

**Comment by git-hulk** [comment] 2024-01-30 03:46
> @git-hulk It looks like no. First is Redis, second is kvrocks ![image](https://private-user-images.githubusercontent.com/32858525/300670400-494d4cd9-6f1e-4c36-9ad4-c5af5cf091e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODY1NjUsIm5iZiI6MTcwNjU4NjI2NSwicGF0aCI6Ii8zMjg1ODUyNS8zMDA2NzA0MDAtNDk0ZDRjZDktNmYxZS00YzM2LTlhZDQtYzVhZjVjZjA5MWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAzNDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNjk1ZGQ1MGUxY2IzYWY5YTk0NzZhZWRlODI1ZWZlMTIxYWE4NDViYWUyNGFiOGRhM2ZkNDhjZWYzMzAxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.begJM7XSuREdnTeeujIV2vK9ZyNgOjDW5R4uMhZOzkg)

Got it, thank you!

**Comment by mapleFU** [comment] 2024-02-26 15:02
I've fixed this via: https://github.com/apache/kvrocks/pull/2113

**Closed as completed by mapleFU** 2024-02-26 15:02 UTC
Labels: bug
