### ISSUE TITLE
Character missing of token in namespace configuration

### ISSUE THREAD

**Issue by iushas** [apache/kvrocks#1879] opened 2023-11-06 07:16 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

所有版本

### Minimal reproduce step

问题一：当密码或者namespace token 有特殊字符时，比如@ # ，在配置文件里需要将密码用双引号引起来，否则kvrocks重启后就无法认证了
1、添加密码
2、修改密码后configrewrite
或者
1、添加namespace
问题2: 当手动将namespace token用双引号引起来以后，如果添加namespace，那么会将老的配置刷掉
比如：
namespace.ns_1  "1234#"
新加一个以后变成了这样
namespace.ns_1  1234#
namespace.ns_2  1234#
这个格式，是无法认证的。 或者kvrocks对特殊字符的认证有问题

### What did you expect to see?

认证通过

### What did you see instead?

认证不通过

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment] 2023-11-06 08:27
Hi @iushas , thanks for your reporting!

It is not a bug. It is expected.

In any line of configuration file, any character after `#` (including `#` itself) will be treated as comments, e.g.
```
config-key config-value # my comments
```

If you want `#` in configuration values, you need to quote them.

And for `@`, I think it works normally.

**Comment by iushas** [comment] 2023-11-06 08:34
这不是bug是什么，这就是bug啊，我密码里面为什么不能含有# ？

**Comment by iushas** [comment] 2023-11-06 08:36
生成配置的时候，把密码全部双引号引起来就好了

**Comment by iushas** [comment] 2023-11-06 08:44
> Hi @iushas , thanks for your reporting!
> 
> It is not a bug. It is expected.
> 
> In any line of configuration file, any character after `#` (including `#` itself) will be treated as comments, e.g.
> 
> ```
> config-key config-value # my comments
> ```
> 
> If you want `#` in configuration values, you need to quote them.
> 
> And for `@`, I think it works normally.

既然客户端可以设置，比如namespace add ns   tokenxx#x@, 那么配置文件就应该要兼容吧

**Comment by PragmaTwice** [comment] 2023-11-06 08:45
Oh sorry, I got your point now.

Do you mean your token is corrupted due to configuration rewriting?

**Comment by iushas** [comment] 2023-11-06 08:58
没有截断，比如我通过namespace add ns_1 1234#56 ，
配置文件里的namespace.ns_1 1234#56

我通过密码1234#56 就是无法认证的。

然后我手动修改配置文件里的配置 namespace.ns_1  "1234#56"，就可以认证了。

但是当再次增加namespace的时候， 我修改的配置又被改回了namespace.ns_1 1234#56

**Comment by PragmaTwice** [comment] 2023-11-06 09:37
Thank you for reporting.

It will be fixed in #1880.

**Closed as completed** 2023-11-06 11:15 UTC
Labels: bug
