### ISSUE TITLE
lua script import error

### ISSUE THREAD

**Issue by i18nsite** [apache/kvrocks#2129] opened 2024-02-29 13:47 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

nightly

### Minimal reproduce step

```
git clone https://atomgit.com/i18n-now/tmp
cd tmp
cat redis.lua | redis-cli -h 127.0.0.1 -p 2901 -a $REDIS_PASSWORD -x FUNCTION LOAD REPLACE
```

### What did you expect to see?

ERR Error while running newfunction lib:redis.register function()requirestwo argument

### What did you see instead?

![image](https://github.com/apache/kvrocks/assets/145643935/7c18cae1-c54d-4e05-947d-a17fbeb5ed15)
https://atomgit.com/i18n-now/tmp/blob/dev/redis.lua
我尝试导入这个lua脚本，redis可以（第二行），kvrocks报错（第一行）

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment] 2024-02-29 13:52
Currently `redis.register_function()` in kvrocks FUNCTION doesn't support the `flags` parameter:

https://atomgit.com/i18n-now/tmp/blob/dev/redis.lua#L83

Please remove it and try again.

**Comment by git-hulk** [comment] 2024-02-29 15:07
The lua function `redis.setresp` will be supported in https://github.com/apache/kvrocks/pull/2130

**Comment by i18nsite** [comment] 2024-03-01 02:42
> Currently `redis.register_function()` in kvrocks FUNCTION doesn't support the `flags` parameter:目前在 `redis.register_function()` kvrocks 中，FUNCTION 不支持以下 `flags` 参数：
> 
> https://atomgit.com/i18n-now/tmp/blob/dev/redis.lua#L83
> 
> Please remove it and try again.请将其删除，然后重试。

明白，建议加一个简单忽略

**Comment by PragmaTwice** [comment] 2024-03-01 15:35
I'll close this issue since it is not a bug. But feel free to open a feature-request issue.

**Closed as completed by PragmaTwice** 2024-03-01 15:35 UTC
Labels: bug

**Comment by i18nsite** [comment] 2024-03-02 10:57
added https://github.com/apache/kvrocks/issues/2133
